-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.24 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.1.0.5464
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for projectm2
CREATE DATABASE IF NOT EXISTS `projectm2` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `projectm2`;

-- Dumping structure for table projectm2.contact
CREATE TABLE IF NOT EXISTS `contact` (
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `email` varchar(150) NOT NULL,
  `subject` varchar(150) NOT NULL,
  `message` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Dumping data for table projectm2.contact: ~3 rows (approximately)
/*!40000 ALTER TABLE `contact` DISABLE KEYS */;
INSERT INTO `contact` (`id`, `name`, `email`, `subject`, `message`, `created_at`) VALUES
	(1, 'Roxana Negru', 'negruroxana1994@gmail.com', 'asdfasdf', 'jhwegwfyfruiorhkrkherhuurtyuewhbk', '2019-05-10 20:07:52');
/*!40000 ALTER TABLE `contact` ENABLE KEYS */;

-- Dumping structure for table projectm2.menu
CREATE TABLE IF NOT EXISTS `menu` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  `link` varchar(150) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table projectm2.menu: ~6 rows (approximately)
/*!40000 ALTER TABLE `menu` DISABLE KEYS */;
INSERT INTO `menu` (`id`, `name`, `link`, `created_at`) VALUES
	(1, 'home', 'index.php', '2019-05-05 18:53:42'),
	(2, 'about', 'about.php', '2019-05-05 18:54:00'),
	(3, 'articles', 'articles.php', '2019-05-05 18:54:10'),
	(4, 'contact', 'contact.php', '2019-05-05 18:54:18'),
	(5, 'login', 'login.php', '2019-05-05 18:54:37');
/*!40000 ALTER TABLE `menu` ENABLE KEYS */;

-- Dumping structure for table projectm2.posts
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(150) NOT NULL,
  `content` text NOT NULL,
  `user_id` int(12) unsigned NOT NULL,
  `category` varchar(100) NOT NULL,
  `thumbnail` varchar(200) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

-- Dumping data for table projectm2.posts: ~13 rows (approximately)
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` (`id`, `title`, `content`, `user_id`, `category`, `thumbnail`, `created_at`) VALUES
	(1, 'How to paint the wall and street', '\r\n<p class="desc">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque\r\n								 laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi\r\n								 architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas\r\n								 consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et\r\n								dolore magnam aliquam quaerat voluptatem.</p>\r\n								<p class="desc">Eerror sit voluptatem accusantium doloremque\r\n								 laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi\r\n								 architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas\r\n								 consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et\r\n								 laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi\r\n								 architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas\r\n								dolore magnam aliquam quaerat voluptatem.</p>\r\n								<h5 class="quoto"><em><i class="ion-quote"></i>Eerror sit voluptatem accusantium doloremque\r\n								 laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi\r\n								 architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas\r\n								 consectetur, adipisci velit\r\n							</em></h5>\r\n', 1, 'Travel', 'blog-3-500x400.jpg', '2019-05-10 18:32:04'),
	(2, 'One more night in the local clubs', '<p class=\'desc\'>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>\r\n<p class=\'desc\'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a sem elit. Duis tempus augue ac mauris vulputate, eget accumsan odio aliquet. Vestibulum semper sem enim, ut rhoncus lectus ultrices ac. Integer in tincidunt sapien, eget blandit tellus. Sed a mi nec nisl consequat semper at a magna. Duis pretium odio ut vulputate imperdiet. Vivamus auctor accumsan tellus ut scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris auctor orci sed justo commodo ullamcorper. Nulla justo eros, mollis vel lacus quis, blandit commodo felis. Morbi efficitur augue quam, quis posuere sapien volutpat et. Curabitur quis leo id dolor scelerisque aliquam nec ac lectus. Sed mauris neque, vehicula ut urna at, consequat rutrum velit. Integer odio tellus, facilisis nec mattis id, mollis non dolor.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Nulla id hendrerit ligula. Nullam scelerisque eros at ex laoreet vestibulum. Morbi molestie vestibulum nisl, ultricies posuere ligula porttitor vel. Nullam id justo ac elit vestibulum iaculis quis vitae dui. Vivamus nec nisl nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec auctor congue sem, a pharetra felis imperdiet eu. Nam in odio ligula. Proin rutrum mi et turpis lacinia, vel aliquam lacus auctor.</em></h5>\r\n', 1, 'Music', 'blog-4-500x400.jpg', '2019-05-10 18:42:24'),
	(3, 'A new festival in your town', '<p class=\'desc\'>Donec cursus erat eu elit auctor, sed efficitur purus aliquam. In lacus erat, volutpat sit amet ipsum eu, luctus viverra nibh. Suspendisse posuere suscipit tristique. Morbi tempor facilisis ante, sit amet lobortis tellus interdum non. Proin volutpat nisl non tellus pellentesque, vitae gravida sapien malesuada. Suspendisse mollis eu dolor eu mattis. Etiam vestibulum consectetur urna ac ultricies. Nam lobortis efficitur eros a pharetra. Maecenas porttitor diam id orci imperdiet molestie.</p>\r\n<p class=\'desc\'>Nullam ut erat magna. Proin a vestibulum nisi, vestibulum porttitor nibh. Curabitur sollicitudin, lacus nec egestas pulvinar, ante mi posuere ante, non sollicitudin nunc lorem sed risus. Fusce suscipit lacus et imperdiet vehicula. Nulla bibendum lacinia tellus, eget porttitor nisi aliquet quis. Proin rutrum sodales velit sit amet ornare. Vivamus luctus eget dolor eget lobortis. In iaculis tincidunt leo accumsan lacinia. Cras rhoncus nisl erat, nec iaculis elit fermentum id.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Sed dapibus dui vel nisi vestibulum, ut blandit mi vehicula. Nulla feugiat, sapien non interdum consequat, nibh nisi hendrerit diam, quis gravida arcu libero fringilla nisl. Morbi lobortis est sit amet massa aliquam, quis ornare nisi gravida. Sed ligula tellus, tincidunt sed sagittis eget, ultricies a enim. Aenean blandit id nunc a interdum. Mauris pretium faucibus dui. In hac habitasse platea dictumst. Sed feugiat felis nec quam maximus, sit amet pharetra purus placerat. Fusce velit felis, pharetra sed ultrices in, pharetra vitae metus. Etiam id ipsum quis lectus vehicula rutrum. Mauris at feugiat erat. Etiam nunc mauris, finibus et cursus vitae, maximus elementum mi.</em></h5>\r\n', 1, 'Lifestyle', 'blog-5-500x400.jpg', '2019-05-10 18:46:18'),
	(4, 'How to make your home modern', '<p class=\'desc\'>Fusce nisl tellus, dignissim quis fermentum in, elementum id sem. Praesent ullamcorper volutpat turpis, nec dictum massa volutpat a. Nam ullamcorper nisl nisi, vel pharetra mauris consequat viverra. Ut pharetra tellus in auctor ornare. Cras mollis sem massa, vitae gravida nibh accumsan quis. Nulla hendrerit ut ligula et lobortis. Etiam et tellus volutpat, imperdiet mauris ut, aliquet purus. Donec sit amet metus nec magna dictum pharetra. Sed in tortor dictum, porttitor neque ut, pellentesque leo. Vestibulum faucibus augue ornare ullamcorper congue. Pellentesque sed pellentesque velit, in tristique libero. Morbi consequat lorem at dolor efficitur luctus. Aenean non magna scelerisque, condimentum nisl et, suscipit nisl. Proin arcu nisl, tristique vel mollis et, condimentum id augue. Morbi tempus vestibulum viverra.</p>\r\n<p class=\'desc\'>Vivamus a auctor massa. Aenean vitae volutpat nulla. Nulla dictum ipsum sed magna mollis pellentesque. Sed blandit id nulla eget commodo. Sed lacus nisi, molestie id feugiat commodo, luctus non odio. Praesent convallis tempus sollicitudin. Nam et ex ac nibh vulputate porta. Mauris pulvinar magna massa, nec egestas mauris placerat in. Integer ac urna laoreet, suscipit nunc et, aliquam nisi. In rhoncus, lacus a ornare dictum, dolor lacus cursus urna, sit amet tristique enim velit ac est. Pellentesque semper arcu ac ultrices fringilla. Donec at malesuada risus, vitae scelerisque magna. Praesent sodales aliquam gravida. Proin placerat, dolor et ultricies sollicitudin, velit eros mattis felis, ac blandit mi ipsum eget tortor.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Ut vestibulum turpis gravida, viverra augue et, ultrices dui. Quisque auctor lorem purus, blandit laoreet quam commodo sed. Aliquam urna augue, facilisis at aliquam et, aliquam vitae nibh. In ac accumsan est. Phasellus molestie vulputate ante id condimentum. Ut eu elit tellus. Nam consectetur felis convallis arcu laoreet placerat. Nunc sit amet odio vestibulum, condimentum diam finibus, scelerisque augue. Nullam pellentesque, risus id tincidunt blandit, diam magna rutrum erat, sit amet fringilla lorem leo sit amet augue. Vestibulum malesuada purus a sapien ullamcorper, vitae tristique nulla convallis. Nam at mollis purus. Maecenas tempus feugiat tortor eget dapibus. Vivamus pretium viverra ante, nec congue lectus venenatis eget.</em></h5>\r\n', 1, 'Design', 'blog-6-500x400.jpg', '2019-05-10 18:47:35'),
	(5, 'How to througn the best engagement party', '<p class=\'desc\'>Suspendisse eu ipsum ac nisl pharetra mollis ut non sapien. Fusce non velit at libero faucibus dapibus. Maecenas eget tempor eros. Proin ullamcorper efficitur massa, eu finibus lacus egestas at. Nam vitae diam libero. Morbi vel finibus purus, sit amet placerat arcu. Vestibulum at libero semper, ullamcorper velit at, sollicitudin nisl.</p>\r\n<p class=\'desc\'>Pellentesque hendrerit orci ligula, nec finibus odio sodales vitae. Maecenas tristique diam velit, vel volutpat arcu commodo at. Praesent interdum tellus vel est posuere egestas. Pellentesque sit amet posuere sapien. Nam interdum lacus nisi, id facilisis mauris dapibus vitae. Curabitur ac dapibus orci, et porttitor ipsum. Integer bibendum, orci eget luctus luctus, lorem urna dictum eros, a venenatis arcu enim sed orci. Fusce euismod commodo ex a eleifend. Fusce ac lorem iaculis, efficitur tellus eu, sodales mauris.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Mauris augue dui, feugiat ut cursus nec, placerat et purus. Sed et eleifend nibh. Suspendisse eu facilisis orci, et condimentum tortor. Quisque auctor pretium faucibus. Nunc in elit finibus, blandit ex vel, fermentum dolor. Cras ultrices urna eu est aliquam, et consequat nisi dapibus. Nulla fermentum venenatis metus, et ornare lectus vestibulum vel. Duis ac efficitur neque, at convallis elit. Vestibulum sagittis cursus lobortis. Aenean non arcu erat. Curabitur eget urna egestas ipsum egestas ornare non ac quam.</em></h5>\r\n', 1, 'Social', 'blog-7-500x400.jpg', '2019-05-10 18:49:54'),
	(6, 'This post is about photography', '<p class=\'desc\'>Integer accumsan ipsum non est vehicula posuere. Mauris nec neque ultricies, eleifend nibh auctor, feugiat arcu. Suspendisse potenti. Nunc elit purus, scelerisque at lacinia tempor, varius in nisi. Etiam maximus eget diam ut hendrerit. Vivamus quis velit pulvinar velit finibus condimentum. Donec nec ante pulvinar, vulputate quam at, accumsan nunc. Phasellus tincidunt ex nisi, at tempus lacus viverra non. Sed cursus volutpat nisi, eu consequat quam. Suspendisse justo nisi, rutrum ut lectus ut, varius rutrum ligula.</p>\r\n<p class=\'desc\'>Morbi et lacus quis tortor ultrices ultrices. Proin cursus, lorem id finibus tincidunt, felis lectus maximus neque, at vestibulum tellus ante vel sapien. Duis sodales odio turpis, sed mollis ligula placerat feugiat. Nulla tellus erat, placerat eget urna vel, mattis pharetra sapien. In ultricies leo porta nulla blandit tincidunt. Integer vitae pretium metus, et lobortis mauris. Vivamus lectus augue, sollicitudin in placerat non, pharetra vel velit. Vestibulum faucibus, erat a gravida commodo, diam dolor maximus purus, id pretium sem urna sit amet enim. Mauris placerat, odio vel porta ultrices, lacus purus porta mauris, sit amet varius lectus elit quis orci. Suspendisse congue nunc vitae facilisis vestibulum. Nam euismod turpis at ligula molestie, vel tincidunt odio ornare.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Nullam quis quam risus. Phasellus et arcu eu nibh porttitor rhoncus interdum at mi. Fusce imperdiet tellus vitae enim blandit semper. Proin pulvinar imperdiet fermentum. Ut id tempor lacus. Nulla tellus mauris, interdum sed augue sed, venenatis faucibus lacus. Nam scelerisque fringilla quam, ut pretium dui consectetur in. Donec at ullamcorper lectus. Pellentesque volutpat rhoncus malesuada. Maecenas efficitur semper nibh sit amet tempus.</em></h5>\r\n', 1, 'Photography', 'recomended-1-200x200.jpg', '2019-05-10 18:50:51'),
	(7, 'Thailanda - Holiday', '<p class=\'desc\'>Ut sit amet turpis molestie, ornare turpis non, vestibulum neque. Integer suscipit dui massa, ut rutrum magna porta vel. Duis interdum semper pharetra. Proin a tellus condimentum, tincidunt leo quis, dapibus mauris. Sed lobortis pharetra imperdiet. Cras malesuada orci sed congue rutrum. Proin sagittis augue sed purus luctus, nec bibendum dui dignissim. In aliquet justo a hendrerit commodo. Proin sit amet porttitor nisl, nec euismod justo. Quisque ullamcorper condimentum est non blandit. Mauris faucibus lobortis tellus, vel porta est. Fusce facilisis porta leo semper feugiat. Curabitur ultricies quam ut bibendum suscipit.</p>\r\n<p class=\'desc\'>Mauris nec velit vel lectus aliquet consequat. Nullam viverra metus felis, eu faucibus nulla maximus sed. Pellentesque tortor nisi, rhoncus nec tempus quis, ornare et orci. Ut ut gravida libero, vitae scelerisque magna. Suspendisse vel tristique quam. Donec ligula est, blandit quis luctus et, sollicitudin a nulla. Nunc quis aliquet nulla. Nunc porttitor leo et urna facilisis ullamcorper. Aenean varius sit amet neque sit amet rutrum. Aenean sollicitudin tortor in odio eleifend tincidunt. Nam dolor velit, suscipit at elementum vitae, feugiat sit amet nunc. Quisque luctus augue arcu, sit amet maximus est pretium ac. Aenean vel hendrerit nunc.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Nunc sit amet elit nec nibh fermentum auctor ut at justo. Suspendisse sem arcu, pretium sed purus non, blandit congue dolor. Ut id orci iaculis, consectetur nisl in, gravida mi. Sed quis lectus feugiat, bibendum arcu quis, ornare nulla. Vestibulum porttitor leo aliquam quam lobortis varius. Fusce elementum placerat massa, ac fringilla ex ultrices sed. Quisque vehicula ac ligula ac hendrerit. In pellentesque lectus quam, a blandit ipsum ullamcorper sit amet. Fusce volutpat facilisis lacus. Sed in odio ac ex volutpat accumsan a eget velit.</em></h5>\r\n', 1, 'Adventure', 'a683aac21fc55061c9b1c808ef205e03.jpg', '2019-05-10 18:53:18'),
	(8, 'This post is about shopping', '<p class=\'desc\'>Cras quam nisi, hendrerit sed massa eget, vulputate luctus leo. Sed ultrices blandit eros non consequat. Nunc at risus in elit ultrices fringilla nec eu nunc. Pellentesque sagittis fringilla dui sit amet fringilla. Sed euismod non libero a dapibus. Morbi nunc dolor, tempor eget pulvinar a, imperdiet id enim. Donec congue libero a tellus consequat egestas. Pellentesque congue fermentum tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut vitae lectus ac eros cursus molestie eu ac enim.</p>\r\n<p class=\'desc\'>Donec erat orci, fermentum a viverra a, posuere id tortor. Morbi vehicula orci erat, interdum facilisis magna dignissim at. Ut aliquam pretium elit, a rhoncus orci porta ac. Suspendisse sit amet sagittis nisl, vel laoreet justo. Morbi vel tincidunt magna. Pellentesque iaculis elit sit amet neque lacinia, at placerat diam condimentum. Phasellus eu cursus metus. Sed eu consequat diam. Integer sapien ex, lacinia id nisi eget, aliquam malesuada nunc. Phasellus efficitur magna ac venenatis convallis. Curabitur nec consequat eros.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Aliquam molestie aliquam mollis. Duis nisl orci, tristique vel mi nec, dignissim consequat ligula. Vestibulum venenatis fermentum venenatis. Aenean nec consectetur risus, non posuere metus. Etiam commodo varius consectetur. Etiam vel tempus nibh, in luctus nulla. Praesent id eleifend nulla. Pellentesque nunc tortor, consectetur vitae ante eget, convallis vestibulum dolor. Maecenas accumsan consectetur sem at efficitur. Nunc neque nunc, imperdiet vel ante vitae, vestibulum pharetra nunc. Vestibulum in posuere orci, vitae tempor tellus.</em></h5>\r\n', 1, 'Shopping', '8a7e6877755483869005c14fd368a4e0.jpg', '2019-05-10 18:55:39'),
	(9, 'Fashion trends 2019', '<p class=\'desc\'>Pellentesque nisi justo, vestibulum non ligula nec, egestas feugiat leo. Fusce aliquet eget urna interdum convallis. Ut ultrices pretium aliquet. Mauris sollicitudin et libero quis facilisis. Praesent tortor ex, consequat non tincidunt in, rhoncus a lectus. Donec non velit vitae massa tempor dapibus. Aenean euismod massa felis, vitae facilisis lacus laoreet nec. Mauris aliquet, diam et lobortis sodales, ex lorem vehicula elit, ac tincidunt mauris nisl vitae mi.</p>\r\n<p class=\'desc\'>Etiam vulputate, diam eget placerat aliquam, purus est dapibus dolor, dictum vestibulum orci dui et diam. Nunc tempor sapien sit amet magna pulvinar blandit. Nunc at aliquam ipsum. Fusce fermentum, sapien vitae congue viverra, dui orci commodo leo, nec bibendum metus ligula vitae dui. Aenean id posuere sem, sed sagittis ante. Cras eget pharetra erat. Pellentesque in ornare libero, nec rhoncus mauris. Vestibulum id ligula ac ipsum posuere ultrices quis vitae mi.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Morbi pellentesque arcu quis turpis viverra tristique. Maecenas maximus a erat blandit egestas. Sed volutpat metus sed magna pulvinar porta. Fusce sed nulla sit amet nibh cursus bibendum. Aliquam ullamcorper nisi magna, in rhoncus felis facilisis vel. Quisque vitae risus non enim dictum cursus. Donec non nulla et elit pulvinar posuere et vel sapien. Nulla erat ipsum, varius in dolor at, efficitur eleifend ante. Etiam ipsum erat, tempus eu ultricies vel, placerat ut orci. Praesent leo neque, tincidunt non commodo eget, euismod vitae mi. Cras ac neque elementum, egestas dui quis, accumsan nulla. Sed varius ante eu est cursus, eget aliquam dolor consequat. Nullam nec erat tempus, vehicula nulla quis, fermentum ligula. Aenean nec ullamcorper felis. Etiam nisi ex, ultricies scelerisque ultrices non, viverra quis sem.</em></h5>\r\n', 1, 'Fashion', 'a8ca7fe36f2e7cf7f66a7991ce088615.jpg', '2019-05-10 18:57:45'),
	(10, 'Creative DIY projects to organize pet supplies', '<p class=\'desc\'>Proin suscipit lobortis arcu a volutpat. Etiam auctor quam eu pellentesque viverra. Nulla facilisi. Etiam sed mauris eu mi commodo mattis. Donec ultrices laoreet ornare. Aenean bibendum arcu ut aliquet gravida. Donec venenatis, nunc ac tempor sollicitudin, ipsum sapien ullamcorper purus, in mattis risus purus non quam. Nullam nec arcu condimentum, condimentum est sed, accumsan turpis. Pellentesque ultricies nunc mauris, quis auctor sem fermentum nec. Donec mattis nisl eros, nec pretium libero pulvinar eu.</p>\r\n<p class=\'desc\'>Etiam ac tristique tellus. Nunc eleifend, dolor a sollicitudin egestas, velit mi placerat eros, sed malesuada nulla dolor quis nibh. Aenean sodales dapibus tortor eu vulputate. Donec blandit consequat lectus in vehicula. Vivamus sed varius erat. Aliquam feugiat scelerisque purus, id sodales justo aliquam sed. Pellentesque ut arcu dui. Nulla elementum, risus ultricies dignissim elementum, lorem mi accumsan dui, vel ornare orci risus ac odio. Ut porttitor eu nibh et eleifend. In nec libero quis arcu facilisis sagittis eget blandit mi. Praesent pulvinar ipsum nibh. Fusce sit amet lacus purus. Mauris eleifend sollicitudin ante vulputate blandit. Maecenas blandit, metus ac semper consequat, est nulla pellentesque elit, sit amet auctor dolor tellus eu justo.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>In hac habitasse platea dictumst. Vivamus dignissim mauris ut felis malesuada, nec condimentum quam blandit. Nam posuere semper consequat. Pellentesque ornare felis at nibh fermentum, ac feugiat velit vehicula. Donec interdum lorem libero, finibus vulputate odio dapibus vel. Mauris at pellentesque nisi. Pellentesque vitae quam blandit, tempor leo sed, sagittis leo. Cras sit amet volutpat quam. Pellentesque sit amet dolor laoreet, auctor felis vitae, faucibus tortor. Sed vitae rhoncus ante. Aenean tristique sapien ex, sed porttitor velit finibus non. Sed et sem rhoncus, varius lectus quis, congue sem.</em></h5>\r\n', 1, 'Pet', '18448e3b3365770bb9fa7d5ff97163f2.jpg', '2019-05-10 19:05:08'),
	(11, 'Travel, Love, Live', '<p class=\'desc\'>Quisque leo turpis, ornare in consequat ut, congue vitae ex. Quisque laoreet risus vitae lectus luctus, eget venenatis mauris congue. Suspendisse in elit lorem. Ut pharetra vehicula varius. Quisque in quam rutrum, semper risus maximus, aliquam urna. Aliquam sit amet tellus mattis, commodo lacus nec, faucibus tortor. Aenean volutpat turpis non erat ultricies placerat. In mattis ante at fringilla venenatis.</p>\r\n<p class=\'desc\'>Morbi egestas mauris vitae risus auctor, vel fringilla felis fringilla. Morbi a nulla lectus. Donec in odio sit amet nibh maximus euismod eu sit amet leo. Curabitur nec consectetur neque, ultrices maximus velit. Mauris tempus libero in ante malesuada consectetur. Duis eu auctor est, sit amet vulputate ipsum. Etiam convallis, dui eu finibus sodales, sem nisl convallis mauris, volutpat sagittis odio purus ac libero. Donec fringilla vel nunc nec dignissim. Aliquam nec mi purus. Aliquam tempus in tellus sit amet auctor.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Nam ultricies aliquam magna ut malesuada. Nam feugiat metus iaculis placerat gravida. Mauris et lacus eget dolor tincidunt ullamcorper. Nulla id purus eu tortor dictum sagittis. Proin pharetra rutrum dapibus. Phasellus fermentum, diam nec vehicula euismod, lectus libero mollis nibh, eu interdum metus enim eget lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ut posuere dolor, nec interdum enim. Proin tristique lacinia odio, eget scelerisque enim placerat id. Cras tristique tempor magna nec suscipit. Sed ut aliquam elit. Nunc viverra tristique dui nec venenatis.</em></h5>\r\n', 1, 'Travel', 'slider-2-1600x800.jpg', '2019-05-10 19:07:27'),
	(12, 'This post is about food', '<p class=\'desc\'>Integer hendrerit turpis ligula, sagittis dictum nisi hendrerit eu. Aenean ac dolor nec libero aliquet sodales vitae et velit. Praesent ac faucibus lacus. In fermentum erat auctor arcu faucibus congue. Morbi dictum lacinia mi ac dignissim. Etiam pharetra egestas leo. Quisque fringilla et quam nec mattis. Cras ex tortor, consequat vitae dictum eget, lacinia malesuada tortor. In aliquam ex id facilisis fringilla. Pellentesque non neque lobortis, aliquet arcu ut, volutpat eros. Donec scelerisque commodo tellus quis aliquet. Aenean tincidunt et dui ut lobortis. Praesent venenatis leo sed diam finibus, id sollicitudin sapien accumsan.</p>\r\n<p class=\'desc\'>Fusce urna mauris, lobortis et sem at, tincidunt fermentum augue. Mauris in accumsan tortor, vel tempor urna. Suspendisse sed sagittis nisi, vitae posuere eros. Morbi consequat metus lacus, eu iaculis nulla viverra id. Donec ac tincidunt augue. Nam elementum lectus eget facilisis tincidunt. Aenean interdum nec risus vel laoreet. Nunc facilisis elit ut est semper, nec elementum augue tempor. Morbi porta, libero a lobortis blandit, velit magna maximus felis, nec consequat est sem ut nisi. Fusce eu commodo ex.</p>\r\n<h5 class=\'quoto\'><em><i class=\'ion-quote\'></i>Sed pulvinar, nisl at varius pharetra, nibh ante imperdiet sapien, ut tempus sem elit eget eros. Proin vitae justo ornare, pulvinar justo ut, tempus quam. Praesent quis consequat metus. Ut egestas ac dui quis placerat. Suspendisse varius augue ut dolor lacinia consequat. Mauris vestibulum quam nec ante accumsan iaculis. Nulla a metus nisl. Etiam vel quam eu metus dignissim cursus. Nullam sed iaculis tortor. Sed tincidunt quis enim at tempus. Proin scelerisque sodales diam sed imperdiet. Nunc rhoncus neque eget tortor dignissim, ut ultrices turpis bibendum.</em></h5>\r\n', 1, 'Travel', 'slider-1-1600x800.jpg', '2019-05-10 19:08:52');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;

-- Dumping structure for table projectm2.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(30) NOT NULL,
  `lastname` varchar(30) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `newsletter_subscription` tinyint(1) DEFAULT '0',
  `is_admin` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table projectm2.users: ~1 rows (approximately)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `password`, `newsletter_subscription`, `is_admin`, `created_at`) VALUES
	(1, 'Roxana-Alexandra', 'Negru', 'negruroxana1994@gmail.com', '74de5c138cd4a2cd2e827dd548131344', 1, 1, '2019-05-10 17:31:08'),
	(2, 'Academia', 'Credis', 'credis@credis.ro', 'aaa5a5bff7a3840f21a0f60a2c119e95', 0, 1, '2019-05-26 21:44:03');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
